Repository Culturale/culturale-server, pull requests merged in 2023-05, with the labels that each got.

#36 298 - Add event to subsription list and fix repositories
  src/application/controllers/event-controller/event-controller.test.ts
  src/application/controllers/event-controller/event-controller.ts
  src/application/controllers/user-controller/user-controller.test.ts
  src/application/controllers/user-controller/user-controller.ts
  src/application/use-cases/makeEventReview/makeReview.ts
  src/domain/entities/event/event.interface.ts
  src/domain/entities/event/event.schema.ts
  src/domain/entities/event/event.ts
  src/domain/entities/index.ts
  src/domain/entities/user/__snapshots__/user.test.ts.snap
  src/domain/entities/user/user.interface.ts
  src/domain/entities/user/user.schema.ts
  src/domain/entities/user/user.ts
  src/domain/repositories/event-repository/event-repository.ts
  src/domain/repositories/index.ts
  src/domain/repositories/user-repository/user-repository.ts
  src/infrastructure/api/event-router/event-router.test.ts
  src/infrastructure/api/event-routes.ts
  src/infrastructure/api/user-routes.ts
  src/infrastructure/dtos/addParticipant.dto.ts
  src/infrastructure/dtos/edit-event.dto.ts
  yarn.lock
Labels: :star: Feature, :warning: Fix

#43 Change id properties of domain entitites
  src/application/controllers/event-controller/event-controller.test.ts
  src/application/controllers/event-controller/event-controller.ts
  src/application/controllers/user-controller/user-controller.test.ts
  src/application/controllers/user-controller/user-controller.ts
  src/application/use-cases/log-in/log-in.ts
  src/domain/entities/chat/__snapshots__/chat.test.ts.snap
  src/domain/entities/chat/chat.interface.ts
  src/domain/entities/chat/chat.ts
  src/domain/entities/event/__snapshots__/event.test.ts.snap
  src/domain/entities/event/event.interface.ts
  src/domain/entities/event/event.ts
  src/domain/entities/message/message.interface.ts
  src/domain/entities/message/message.ts
  src/domain/entities/review/review.interface.ts
  src/domain/entities/review/review.ts
  src/domain/entities/user/__snapshots__/user.test.ts.snap
  src/domain/entities/user/user.interface.ts
  src/domain/entities/user/user.ts
  src/infrastructure/api/user-router/user-routes.test.ts
Labels: :wrench: Refactor

#41 Set up K8s deployment files
  .github/workflows/cd.yml
  .github/workflows/k8s-cd.yml
  k8s/culturale-ingress.yml
  k8s/culturale-server.yml
  k8s/mongodb-config.yml
  k8s/mongodb-deployment.yml
  k8s/mongodb-pvc.yml
  k8s/mongodb-secret.yml
  k8s/server-config.yml
  k8s/server-secret.yml
  k8s/storage-class.yml
Labels: :floppy_disk: Setup
